# Generated by Django 4.1.6 on 2023-04-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_terapi', '0002_alter_appointment_slot_waktu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slot_waktu',
            field=models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00')], max_length=50, verbose_name='Slot Waktu'),
        ),
    ]
