# Generated by Django 4.1.6 on 2023-04-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_terapi', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='catatan_terapi',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Catatan Terapi'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='evaluasi_terapi',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Evaluasi Terapi'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pemeriksaan',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Pemeriksaan'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tindakan',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Tindakan'),
        ),
    ]
