# Generated by Django 4.1.6 on 2023-04-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_terapi', '0007_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='verifikasi',
            field=models.BooleanField(default=False, verbose_name='Verifikasi Rekam Medis'),
        ),
    ]
