# Generated by Django 4.1.6 on 2023-04-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_terapi', '0008_appointment_verifikasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='alasan_tolak',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Alasan Tolak'),
        ),
    ]
