# Generated by Django 4.1.6 on 2023-04-20 10:27

import account.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('role', models.CharField(max_length=50, verbose_name='role')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Wali_Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Nama')),
                ('jenis_kelamin', models.CharField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=20, null=True, verbose_name='Jenis Kelamin')),
                ('hubungan', models.CharField(max_length=50, null=True, verbose_name='Hubungan')),
                ('nomor_whatsapp', models.CharField(max_length=25, null=True, verbose_name='Nomor WhatsApp')),
                ('alamat', models.CharField(max_length=250, null=True, verbose_name='Alamat')),
                ('email_wali', models.EmailField(max_length=254)),
                ('pekerjaan', models.CharField(max_length=50, null=True, verbose_name='Pekerjaan')),
                ('user', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Wali_Pasien',
            },
        ),
        migrations.CreateModel(
            name='Terapis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Nama')),
                ('spesialisasi', models.CharField(choices=[('Fisioterapi', 'Fisioterapi'), ('Terapi Okupasi', 'Terapi Okupasi'), ('Terapi Wicara', 'Terapi Wicara')], max_length=50, null=True, verbose_name='Spesialisasi')),
                ('jadwal_hari', models.JSONField(default=account.models.jsonfield_default_value, verbose_name='Jadwal Hari')),
                ('user', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Terapis',
            },
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Nama')),
                ('tanggal_lahir', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date.today), django.core.validators.MinValueValidator(datetime.date(1923, 4, 20))])),
                ('tempat_lahir', models.CharField(max_length=50, null=True, verbose_name='Tempat Lahir')),
                ('jenis_kelamin', models.CharField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=20, null=True, verbose_name='Jenis Kelamin')),
                ('nomor_whatsapp', models.CharField(max_length=25, null=True, verbose_name='Nomor WhatsApp')),
                ('alamat', models.CharField(max_length=250, null=True, verbose_name='Alamat')),
                ('pekerjaan', models.CharField(max_length=50, null=True, verbose_name='Pekerjaan')),
                ('status', models.CharField(choices=[('Umum', 'Umum'), ('Mahasiswa', 'Mahasiswa'), ('Pekerja di Vokasi UI', 'Pekerja di Vokasi UI'), ('Pekerja di UI non Vokasi', 'Pekerja di UI non Vokasi')], max_length=50, null=True, verbose_name='Status')),
                ('user', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wali', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wali', to='account.wali_pasien')),
            ],
            options={
                'db_table': 'Pasien',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Nama')),
                ('user', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
    ]
