# Generated by Django 4.1.6 on 2023-04-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='tipe',
            field=models.CharField(choices=[('Anak', 'Anak'), ('Dewasa', 'Dewasa')], max_length=50, null=True, verbose_name='Tipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Pasien', 'Pasien'), ('Terapis', 'Terapis')], max_length=50, verbose_name='role'),
        ),
    ]
