# Generated by Django 4.1.6 on 2023-04-21 09:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_pasien_tipe_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='tanggal_lahir',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date.today), django.core.validators.MinValueValidator(datetime.date(1923, 4, 21))]),
        ),
    ]
