# Generated by Django 4.1.6 on 2023-04-21 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_pasien_tanggal_lahir'),
        ('daftar_terapi', '0006_appointment_catatan_terapi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekamMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunjungan', models.ManyToManyField(related_name='kunjungan', to='daftar_terapi.appointment')),
                ('pasien', models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='account.pasien')),
                ('terapis', models.ManyToManyField(related_name='terapis', to='account.terapis')),
            ],
            options={
                'db_table': 'RekamMedis',
            },
        ),
    ]
